spring:
  application:
    name: v1-notification-service
  profiles:
    active: ${PROFILE}
  config:
    import: optional:configserver:https://api.xquare.app/cloud-config/
  cloud:
    config:
      username: ${CLOUD_CONFIG_USERNAME}
      password: ${CLOUD_CONFIG_PASSWORD}
server:
  port: 8081
