name: Build for Prod
on:
  push:
    tags:
      - v*.*.*

env:
  SERVICE_NAME: notification
  SERVICE_TYPE: be

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    outputs:
      version: ${{ steps.get_version.outputs.BRANCH_NAME }}

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'
          
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --no-daemon
            
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USER}}/${{env.SERVICE_NAME}}-${{env.SERVICE_TYPE}}:${{ steps.get_version.outputs.VERSION }}
          build-args : |
            DB_URL=${{secrets.DB_URL_PROD}}
            DB_USERNAME=${{secrets.DB_USERNAME_PROD}}
            DB_PASSWORD=${{secrets.DB_PASSWORD_PROD}}
            DB_NAME=${{secrets.DB_NAME_PROD}}

            FCM_VALUE=${{secrets.FCM_VALUE_PROD}}
            
            AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY_PROD}}
            AWS_SECRET_KEY=${{secrets.AWS_SECRET_KEY_PROD}}
            
            USER_URL=${{secrets.USER_SERVICE_HOST}}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITOPS_DEPLOY_STAGE_TOKEN }}
          repository: team-xquare/xquare-gitops-repo-production
          event-type: update_image
          client-payload: '{
                          "ref": "${{ github.ref }}", 
                          "version":  "${{ steps.get_version.outputs.VERSION }}",
                          "service_name": "${{env.SERVICE_NAME}}",
                          "service_type": "${{env.SERVICE_TYPE}}"
                          }'
