name: Build for Stage
on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: notification
  SERVICE_TYPE: be

jobs:
  build:
    environment: stag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    outputs:
      version: ${{ steps.get_version.outputs.BRANCH_NAME }}

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --no-daemon

      - name: Login to ECR
        id: ecr
        uses: elgohr/ecr-login-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_STAGE }}
          secret_access_key: ${{ secrets.AWS_SECRET_KEY_STAGE }}
          region: ${{ secrets.AWS_REGION }}

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.ECR_REPO_NAME }}
          username: ${{ steps.ecr.outputs.username }}
          password: ${{ steps.ecr.outputs.password }}
          registry: ${{ steps.ecr.outputs.registry }}
          buildargs: |
            DB_URL=${{secrets.DB_URL_STAGE}}
            DB_USERNAME=${{secrets.DB_USERNAME_STAGE}}
            DB_PASSWORD=${{secrets.DB_PASSWORD_STAGE}}
            DB_NAME=${{secrets.DB_NAME_STAGE}}

            FCM_VALUE=${{secrets.FCM_VALUE_STAGE}}

            AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY_STAGE}}
            AWS_SECRET_KEY=${{secrets.AWS_SECRET_KEY_STAGE}}
            
            USER_URL=${{secrets.USER_SERVICE_HOST_STAG}}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITOPS_DEPLOY_STAGE_TOKEN }}
          repository: team-xquare/xquare-gitops-repo-staging
          event-type: update_image
          client-payload: '{"ref": "${{ github.ref }}", 
                          "version": "${{ github.sha }}",
                          "service_name": "${{env.SERVICE_NAME}}",
                          "service_type": "${{env.SERVICE_TYPE}}"}'
